// Ensure you have PAYSTACK_SECRET_KEY in your .env file
const PAYSTACK_SECRET_KEY = process.env.PAYSTACK_SECRET_KEY as string;
const BASE_URL = 'https://api.paystack.co';

if (!PAYSTACK_SECRET_KEY) {
  console.warn('WARNING: PAYSTACK_SECRET_KEY is not defined in environment variables.');
}

const getHeaders = () => ({
  'Authorization': `Bearer ${PAYSTACK_SECRET_KEY}`,
  'Content-Type': 'application/json',
});

/**
 * Step 1: Initialize a transaction for the attendee to pay
 * @param email Attendee's email address
 * @param amount Amount in Naira (will be converted to Kobo internally)
 * @param orderRef The unique FLW reference generated by the backend
 */
export const initializeTransaction = async (email: string, amount: number, orderRef: string) => {
  try {
    const response = await fetch(`${BASE_URL}/transaction/initialize`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        email,
        amount: Math.round(amount * 100), // Paystack requires amount in Kobo
        reference: orderRef,
        // Optional: Add a callback URL to redirect the user after payment
        // callback_url: `${process.env.FRONTEND_URL}/tracking/${orderRef}`
      }),
    });

    const data = await response.json();

    if (!response.ok || !data.status) {
      throw new Error(`Paystack Init Error: ${data.message || 'Failed to initialize transaction'}`);
    }

    return data.data; // Contains authorization_url, access_code, and reference
  } catch (error) {
    console.error('Error in initializeTransaction:', error);
    throw error;
  }
};

/**
 * Step 1b: Verify a transaction after user redirects back
 * @param reference The Paystack reference
 */
export const verifyTransaction = async (reference: string) => {
  try {
    const response = await fetch(`${BASE_URL}/transaction/verify/${encodeURIComponent(reference)}`, {
      method: 'GET',
      headers: getHeaders(),
    });

    const data = await response.json();

    if (!response.ok || !data.status) {
      throw new Error(`Paystack Verify Error: ${data.message || 'Failed to verify transaction'}`);
    }

    return data.data; // Contains status, amount, etc.
  } catch (error) {
    console.error('Error in verifyTransaction:', error);
    throw error;
  }
};

/**
 * Step 2: Create a Transfer Recipient for the Vendor
 * This must be done before you can transfer funds to their bank account.
 * You can store the returned RCP_ code in the vendor_profiles table to avoid recreating it.
 */
export const createTransferRecipient = async (bankCode: string, accountNumber: string, accountName: string) => {
  try {
    const response = await fetch(`${BASE_URL}/transferrecipient`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        type: 'nuban',
        name: accountName,
        account_number: accountNumber,
        bank_code: bankCode,
        currency: 'NGN',
      }),
    });

    const data = await response.json();

    if (!response.ok || !data.status) {
      throw new Error(`Paystack Recipient Error: ${data.message || 'Failed to create transfer recipient'}`);
    }

    return data.data; // Contains recipient_code (RCP_xxxxxx)
  } catch (error) {
    console.error('Error in createTransferRecipient:', error);
    throw error;
  }
};

/**
 * Step 3: Initiate the Payout to the Vendor
 * This is called only when the order is marked as 'completed' by both parties.
 * @param recipientCode The RCP_ code generated from createTransferRecipient
 * @param amount Amount to pay the vendor in Naira (Platform fees should be deducted prior to passing this parameter)
 * @param orderRef The unique FLW reference (Used as idempotency key)
 */
export const initiatePayout = async (recipientCode: string, amount: number, orderRef: string) => {
  try {
    const response = await fetch(`${BASE_URL}/transfer`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        source: 'balance', 
        amount: Math.round(amount * 100), // Convert to Kobo
        recipient: recipientCode,
        reason: `FlowMart Payout for Order: ${orderRef}`,
        reference: `PAYOUT-${orderRef}`, // Prevents duplicate payouts if the network fails
      }),
    });

    const data = await response.json();

    if (!response.ok || !data.status) {
      throw new Error(`Paystack Transfer Error: ${data.message || 'Failed to initiate payout'}`);
    }

    return data.data; // Contains transfer status, transfer_code, etc.
  } catch (error) {
    console.error('Error in initiatePayout:', error);
    throw error;
  }
};
